# JSON access log configuration

log_format json_combined escape=json '{ "time_local": "$time_local", "remote_addr": "$remote_addr", "http_x_forwarded_for": "$http_x_forwarded_for", "request": "$request", "status": "$status", "body_bytes_sent": "$body_bytes_sent", "http_referer": "$http_referer", "http_user_agent": "$http_user_agent", "request_time": "$request_time" }';

# Nginx virtual host configuration

server {
  listen 80;

  root /srv/www/server11.example.com/public;
  index index.html;

  server_name server11.example.com www.server11.example.com;

  # Logs
  access_log /srv/www/server11.example.com/log/access.log json_combined;
  error_log /srv/www/server11.example.com/log/error.log;
}
